model:
  whisper: 'openai/whisper-large'
  bilstm:
    hidden_size: 64

data:
  root: '/netscratch/herzig/datasets/BabyCry_no_augment'

train:
  batch_size: 128
  epochs: 100
  accelerator: 'gpu'
  strategy: 'ddp'
